export const promoCodes = [
  {
    code: "WELCOME10",
    discountType: "PERCENTAGE" as const,
    discountValue: 10,
    minOrderTotal: 20,
    targetSegment: "ALL" as const,
    isActive: true,
    daysUntilExpiry: 90,
    usageLimitTotal: null as number | null,
    usageLimitPerUser: 1,
  },
  {
    code: "VIP20",
    discountType: "PERCENTAGE" as const,
    discountValue: 20,
    minOrderTotal: 30,
    targetSegment: "TOP_30" as const,
    isActive: true,
    daysUntilExpiry: 60,
    usageLimitTotal: 100,
    usageLimitPerUser: 3,
  },
  {
    code: "COMEBACK10JD",
    discountType: "FIXED" as const,
    discountValue: 10,
    minOrderTotal: 25,
    targetSegment: "BOTTOM_30" as const,
    isActive: true,
    daysUntilExpiry: 45,
    usageLimitTotal: null as number | null,
    usageLimitPerUser: 1,
  },
  {
    code: "SUMMER25",
    discountType: "PERCENTAGE" as const,
    discountValue: 25,
    minOrderTotal: 15,
    targetSegment: "ALL" as const,
    isActive: true,
    daysUntilExpiry: -10, // already expired, for testing expiry logic
    usageLimitTotal: 200,
    usageLimitPerUser: 2,
  },
  {
    code: "FLASH5JD",
    discountType: "FIXED" as const,
    discountValue: 5,
    minOrderTotal: 10,
    targetSegment: "ALL" as const,
    isActive: false, // manually disabled, for testing the active toggle
    daysUntilExpiry: 30,
    usageLimitTotal: 50,
    usageLimitPerUser: 1,
  },
];
