export const supportTicketTemplates = [
  {
    category: "Order Issue",
    status: "RESOLVED" as const,
    subjectEn: "My order arrived with a damaged box",
    subjectAr: "وصل طلبي وعبوته تالفة",
    messageEn: "Hi, the outer packaging on my last order was crushed and one item looked scratched. Could you help?",
    messageAr: "مرحبًا، وصلت عبوة الطلب الأخير مضغوطة وأحد المنتجات يبدو عليه خدش. هل يمكن المساعدة؟",
    replyEn: "So sorry about that! We've issued store credit to your account to cover the item - thanks for letting us know.",
    replyAr: "نعتذر عن ذلك! تم إضافة رصيد متجر لحسابك لتغطية قيمة المنتج - شكرًا لإبلاغنا.",
  },
  {
    category: "Product Question",
    status: "CLOSED" as const,
    subjectEn: "Is this serum safe to use during pregnancy?",
    subjectAr: "هل هذا السيروم آمن للاستخدام أثناء الحمل؟",
    messageEn: "I love your Retinol Renewal Night Serum but read retinol isn't recommended during pregnancy. Can you confirm?",
    messageAr: "أحب سيروم الريتينول الليلي المجدد لكنني قرأت أن الريتينول غير موصى به أثناء الحمل. هل يمكن التأكيد؟",
    replyEn: "Great question - we'd recommend checking with your doctor first, and in the meantime our Niacinamide serum is a pregnancy-safe alternative.",
    replyAr: "سؤال ممتاز - ننصح باستشارة طبيبكِ أولاً، وفي هذه الأثناء يمكن تجربة سيروم النياسيناميد كبديل آمن أثناء الحمل.",
  },
  {
    category: "Return / Refund",
    status: "IN_PROGRESS" as const,
    subjectEn: "Wrong shade delivered",
    subjectAr: "تم توصيل درجة لون خاطئة",
    messageEn: "I ordered the Ivory shade of the Hydra-Glow Foundation but received a different one. I'd like a replacement.",
    messageAr: "طلبت درجة عاجي من كريم أساس هيدرا-جلو لكن وصلتني درجة مختلفة. أرغب في استبدالها.",
    replyEn: "Thanks for flagging this - we've started a return request on your order and a replacement is on its way.",
    replyAr: "شكرًا لإبلاغنا - تم فتح طلب إرجاع لطلبكِ والبديل في طريقه إليكِ.",
  },
  {
    category: "Loyalty & Wallet",
    status: "OPEN" as const,
    subjectEn: "Loyalty points not showing after my last order",
    subjectAr: "نقاط الولاء لم تظهر بعد طلبي الأخير",
    messageEn: "My order was delivered three days ago but I don't see the loyalty points credited to my account yet.",
    messageAr: "تم توصيل طلبي منذ ثلاثة أيام لكنني لا أرى نقاط الولاء مضافة إلى حسابي بعد.",
    replyEn: null,
    replyAr: null,
  },
  {
    category: "Shipping",
    status: "ASSIGNED" as const,
    subjectEn: "Can I change my delivery address after ordering?",
    subjectAr: "هل يمكنني تغيير عنوان التوصيل بعد إتمام الطلب؟",
    messageEn: "I just placed an order but need to change the delivery address to my work address instead.",
    messageAr: "قمت للتو بطلب لكنني أحتاج لتغيير عنوان التوصيل إلى عنوان عملي بدلاً منه.",
    replyEn: null,
    replyAr: null,
  },
  {
    category: "General",
    status: "OPEN" as const,
    subjectEn: "Do you ship to Aqaba year-round?",
    subjectAr: "هل يتوفر التوصيل إلى العقبة على مدار السنة؟",
    messageEn: "Just checking whether shipping to Aqaba ever gets suspended during peak season.",
    messageAr: "أتساءل فقط إن كان التوصيل إلى العقبة يتوقف أحيانًا في مواسم الذروة.",
    replyEn: null,
    replyAr: null,
  },
  {
    category: "Order Issue",
    status: "RESOLVED" as const,
    subjectEn: "Missing item from my order",
    subjectAr: "منتج مفقود من طلبي",
    messageEn: "My order confirmation listed 3 items but only 2 arrived. The Rose Petal Blush seems to be missing.",
    messageAr: "تأكيد طلبي يذكر 3 منتجات لكن وصل فقط 2. يبدو أن أحمر الخدود - بتلة الورد مفقود.",
    replyEn: "Apologies for the mix-up! We've shipped the missing item separately at no extra cost, it should arrive shortly.",
    replyAr: "نعتذر عن هذا الخطأ! تم شحن المنتج المفقود بشكل منفصل دون أي تكلفة إضافية، وسيصل قريبًا.",
  },
] as const;
